package com.example.data.models

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "attendance")
data class Attendance(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val userId: String,
    val labourId: Int,
    val siteId: Int,
    val date: String,             // YYYY-MM-DD
    val status: String,           // "Present", "Half Day", "Absent" for backward compatibility
    val attendanceType: String = "Full Day", // "Full Day", "Half Day", "Absent"
    val dailyRate: Double = 0.0,
    val earnedAmount: Double = 0.0,
    val finalized: Boolean = true,
    val finalizedAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis(),
    val generatedPaymentId: Int? = null,
    val createdAt: Long = System.currentTimeMillis(),
    val lastEditedAt: Long? = null,
    val lastEditedBy: String? = null,
    val autoGenerated: Boolean = false,
    val version: Int = 1
)
